<?php

namespace HBMigrator\Exporters;

use HBMigrator\ArtifactManager;
use HBMigrator\Checkpoint;
use HBMigrator\PipelineController;

class WxrExporter {

	private const BATCH_SIZE_DEFAULT = 500;
	private const EXPORT_FILENAME    = 'hbm-export.xml';

	/**
	 * AS action callback: hbm_export_wxr_batch($last_post_id, $attempt).
	 *
	 * $last_post_id maps to batch_offset in hbm_queue and drives pagination.
	 * header_written is derived from batch_offset === 0 (no schema column needed).
	 */
	public static function process_batch( int $last_post_id, int $attempt ): void {
		try {
			global $wpdb;
			$batch_size     = (int) apply_filters( 'hbm_wxr_batch_size', self::BATCH_SIZE_DEFAULT );
			$header_written = $last_post_id > 0;
			$out            = ArtifactManager::get_export_dir() . self::EXPORT_FILENAME;
			$mode           = $header_written ? 'a' : 'w';

			$fh = fopen( $out, $mode );
			if ( false === $fh ) {
				throw new \RuntimeException( "Cannot open WXR file for writing: $out" );
			}

			if ( ! $header_written ) {
				fwrite( $fh, self::get_xml_header() );
			}

			$posts = $wpdb->get_results(
				$wpdb->prepare(
					"SELECT * FROM {$wpdb->posts} WHERE ID > %d AND post_status NOT IN ('auto-draft','trash') ORDER BY ID LIMIT %d",
					$last_post_id,
					$batch_size
				)
			);

			if ( empty( $posts ) ) {
				// No more posts — write the closing XML and finish.
				fwrite( $fh, self::get_xml_footer() );
				fclose( $fh );
				PipelineController::stage_complete( 'wxr' );
				return;
			}

			foreach ( $posts as $post ) {
				fwrite( $fh, self::post_to_item_xml( $post ) );
			}

			$new_last_id = (int) end( $posts )->ID;
			fclose( $fh );
			Checkpoint::set_offset( 'wxr', $new_last_id );
			as_enqueue_async_action( 'hbm_export_wxr_batch', [ $new_last_id, 0 ], 'hb-migrator' );

		} catch ( \Throwable $e ) {
			PipelineController::handle_batch_failure( 'wxr', $e, [ $last_post_id, $attempt ] );
		}
	}

	private static function get_xml_header(): string {
		$site_url  = get_bloginfo_rss( 'url' );
		$site_name = get_bloginfo_rss( 'name' );
		$wxr_ver   = '1.2';
		return <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<!-- WordPress eXtended RSS file - generated by HB Migrator -->
<!-- DO NOT EDIT THIS FILE -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/{$wxr_ver}/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/{$wxr_ver}/"
>
<channel>
	<title>{$site_name}</title>
	<link>{$site_url}</link>
	<description></description>
	<wp:wxr_version>{$wxr_ver}</wp:wxr_version>
	<wp:base_site_url>{$site_url}</wp:base_site_url>
	<wp:base_blog_url>{$site_url}</wp:base_blog_url>

XML;
	}

	private static function get_xml_footer(): string {
		return "\n</channel>\n</rss>\n";
	}

	/**
	 * Convert a WP_Post-like object to a WXR <item> element.
	 */
	private static function post_to_item_xml( object $post ): string {
		$cdata = fn( string $s ) => '<![CDATA[' . $s . ']]>';
		$esc   = fn( string $s ) => htmlspecialchars( $s, ENT_XML1 | ENT_QUOTES, 'UTF-8' );

		$categories = self::get_post_terms_xml( (int) $post->ID );
		$meta       = self::get_post_meta_xml( (int) $post->ID );

		return "\t<item>\n" .
			"\t\t<title>" . $cdata( $post->post_title ) . "</title>\n" .
			"\t\t<link>" . $esc( get_permalink( $post->ID ) ) . "</link>\n" .
			"\t\t<pubDate>" . $esc( $post->post_date_gmt ) . "</pubDate>\n" .
			"\t\t<dc:creator>" . $cdata( get_the_author_meta( 'login', (int) $post->post_author ) ) . "</dc:creator>\n" .
			"\t\t<content:encoded>" . $cdata( $post->post_content ) . "</content:encoded>\n" .
			"\t\t<excerpt:encoded>" . $cdata( $post->post_excerpt ) . "</excerpt:encoded>\n" .
			"\t\t<wp:post_id>" . (int) $post->ID . "</wp:post_id>\n" .
			"\t\t<wp:post_date><![CDATA[" . $post->post_date . "]]></wp:post_date>\n" .
			"\t\t<wp:post_date_gmt><![CDATA[" . $post->post_date_gmt . "]]></wp:post_date_gmt>\n" .
			"\t\t<wp:comment_status><![CDATA[" . $post->comment_status . "]]></wp:comment_status>\n" .
			"\t\t<wp:ping_status><![CDATA[" . $post->ping_status . "]]></wp:ping_status>\n" .
			"\t\t<wp:post_name><![CDATA[" . $post->post_name . "]]></wp:post_name>\n" .
			"\t\t<wp:status><![CDATA[" . $post->post_status . "]]></wp:status>\n" .
			"\t\t<wp:post_parent>" . (int) $post->post_parent . "</wp:post_parent>\n" .
			"\t\t<wp:menu_order>" . (int) $post->menu_order . "</wp:menu_order>\n" .
			"\t\t<wp:post_type><![CDATA[" . $post->post_type . "]]></wp:post_type>\n" .
			"\t\t<wp:post_password><![CDATA[" . $post->post_password . "]]></wp:post_password>\n" .
			"\t\t<wp:is_sticky>0</wp:is_sticky>\n" .
			$categories .
			$meta .
			"\t</item>\n";
	}

	private static function get_post_terms_xml( int $post_id ): string {
		$taxonomies = get_object_taxonomies( get_post_type( $post_id ) );
		$out        = '';
		foreach ( $taxonomies as $tax ) {
			$terms = wp_get_object_terms( $post_id, $tax );
			if ( is_wp_error( $terms ) ) {
				continue;
			}
			foreach ( $terms as $term ) {
				$out .= "\t\t<category domain=\"" . htmlspecialchars( $tax, ENT_XML1 ) . '" nicename="' . htmlspecialchars( $term->slug, ENT_XML1 ) . '"><![CDATA[' . $term->name . "]]></category>\n";
			}
		}
		return $out;
	}

	private static function get_post_meta_xml( int $post_id ): string {
		$meta = get_post_meta( $post_id );
		$out  = '';
		foreach ( $meta as $key => $values ) {
			foreach ( $values as $value ) {
				$out .= "\t\t<wp:postmeta>\n" .
					"\t\t\t<wp:meta_key><![CDATA[" . $key . "]]></wp:meta_key>\n" .
					"\t\t\t<wp:meta_value><![CDATA[" . $value . "]]></wp:meta_value>\n" .
					"\t\t</wp:postmeta>\n";
			}
		}
		return $out;
	}
}
